---
# Tell the yaml linter to ignore long lines
# yamllint disable rule:line-length

# Clean up the existing keytabs
# Determine if the realm-capsule user exists
# If the user exists, get the existing keytab
# If the user does not exist, call prepare realm - this pulls the keytab
# Copy the keytab to the appropriate locations.

- name: "Assume the foreman proxy realm user does not exist" # noqa var-naming[no-role-prefix]
  ansible.builtin.set_fact:
    realm_user_exists: false
  tags:
    - tags_satellite_pre
    - tags_satellite_pre_idm_integration
    - tags_satellite_before_sync

- name: "Set default rex_kerberos_sudo_rule for backwards compatibility" # noqa var-naming[no-role-prefix]
  when: rex_kerberos_sudo_rule_name is not defined
  ansible.builtin.set_fact:
    rex_kerberos_sudo_rule_name: "satellite_rex_kerberos"
    rex_kerberos_sudo_rule_order: "102"

- name: "Clean up old keytabs"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/foreman-proxy/freeipa.keytab"
    - "~/freeipa.keytab"
  tags:
    - tags_satellite_pre
    - tags_satellite_pre_idm_integration
    - tags_satellite_before_sync

- name: "Determine if the foreman-proxy realm user exists - normally realm-capsule" # noqa: command-instead-of-shell risky-shell-pipe # noqa var-naming[no-role-prefix]
  ansible.builtin.shell: "echo '{{ ipa_admin_password }}' | kinit {{ ipa_admin_principal }}; echo '{{ ipa_admin_password }}' | ipa user-find {{ foreman_proxy_realm_principal }}"
  register: fpr_user_find
  changed_when: fpr_user_find.rc == 0
  failed_when: (fpr_user_find.stdout_lines | length) == 0
  tags:
    - tags_satellite_pre
    - tags_satellite_pre_idm_integration
    - tags_satellite_before_sync

- name: "Evaluate search" # noqa var-naming[no-role-prefix]
  when: ('1 user matched') in fpr_user_find.stdout
  ansible.builtin.set_fact:
    realm_user_exists: true
  tags:
    - tags_satellite_pre
    - tags_satellite_pre_idm_integration
    - tags_satellite_before_sync

- name: "If the foreman-proxy realm user exists, retrieve the keytab"
  when: realm_user_exists
  ansible.builtin.include_tasks: 'get_foreman_proxy_keytab.yml'
  tags:
    - tags_satellite_pre
    - tags_satellite_pre_idm_integration
    - tags_satellite_before_sync

- name: "If the foreman-proxy realm user does not exist, prepare the realm"
  when: not realm_user_exists
  block:

    - name: "Setup satellite realm user"  # noqa: command-instead-of-shell risky-shell-pipe # noqa var-naming[no-role-prefix]
      ansible.builtin.shell: "echo '{{ ipa_admin_password }}' | kinit {{ ipa_admin_principal }}; echo '{{ ipa_admin_password }}' | /usr/sbin/foreman-prepare-realm {{ ipa_admin_principal }} {{ foreman_proxy_realm_principal }}"
      register: fpr_prepare_realm
      changed_when: fpr_prepare_realm.rc == 0
      tags:
        - tags_satellite_pre
        - tags_satellite_pre_idm_integration
        - tags_satellite_before_sync

    - name: "Determine keytab download file" # noqa var-naming[no-role-prefix]
      ansible.builtin.set_fact:
        freeipa_keytab_file: "{{ fpr_prepare_realm.stdout_lines[-1].split()[-1] }}"

    - name: "Wait for keytab generation and retrieval"
      ansible.builtin.wait_for:
        path: "{{ freeipa_keytab_file }}"
      tags:
        - tags_satellite_pre
        - tags_satellite_pre_idm_integration
        - tags_satellite_before_sync

    - name: "Move the keytab to a known location"
      ansible.builtin.copy:
        src: "{{ freeipa_keytab_file }}"
        dest: "/root/freeipa.keytab"
        mode: "0600"
        remote_src: true
      tags:
        - tags_satellite_pre
        - tags_satellite_pre_idm_integration
        - tags_satellite_before_sync

- name: "Ensure that the realm user for Satellite has sudo permissions for use with remote execution."
  when:
    - rex_kerberos_enabled
    - realm_user_exists
  redhat.rhel_idm.ipasudorule:
    ipaadmin_principal: "{{ ipa_admin_principal }}"
    ipaadmin_password: "{{ ipa_admin_password }}"
    name: "{{ rex_kerberos_sudo_rule_name }}"
    order: "{{ rex_kerberos_sudo_rule_order }}"
    description: "Allow the foreman-proxy realm user to run sudo commands for remote execution"
    hostcategory: "all"
    cmdcategory: "all"       # use this to enable unrestricted access to all privileged commands  - HANDLE WITH CARE
    runasusercategory: "all"
    runasgroupcategory: "all"
    sudooption:
      - "!authenticate"
    state: "present"
    user:
      - "{{ foreman_proxy_realm_principal }}"

- name: "Ensure the foreman-proxy directory exists"
  ansible.builtin.file:
    path: "/etc/foreman-proxy"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  tags:
    - tags_satellite_pre
    - tags_satellite_pre_idm_integration
    - tags_satellite_before_sync

- name: "Move the keytab to the foreman-proxy directory"
  ansible.builtin.copy:
    src: "/root/freeipa.keytab"
    dest: /etc/foreman-proxy/freeipa.keytab
    owner: foreman-proxy
    group: foreman-proxy
    mode: "0600"
    remote_src: true
  tags:
    - tags_satellite_pre
    - tags_satellite_pre_idm_integration
    - tags_satellite_before_sync

- name: "Test the new keytab" # noqa: no-changed-when risky-shell-pipe # noqa var-naming[no-role-prefix]
  ansible.builtin.command: "kinit -kt /etc/foreman-proxy/freeipa.keytab {{ foreman_proxy_realm_principal }}"
  register: result
  tags:
    - tags_satellite_pre
    - tags_satellite_pre_idm_integration
    - tags_satellite_before_sync

- name: "Assert Success"
  ansible.builtin.assert:
    that:
      - result.stdout == ""
  tags:
    - tags_satellite_pre
    - tags_satellite_pre_idm_integration
    - tags_satellite_before_sync
