---

- name: "Set _satpre_satellite_installed to false" # noqa var-naming[no-role-prefix]
  ansible.builtin.set_fact:
    _satpre_satellite_installed: false
  tags:
    - tags_satellite_pre
    - tags_satellite_before_sync


- name: "Has satellite-installer been run"
  block:

    - name: "Get the state of the foreman service" # noqa var-naming[no-role-prefix]
      ansible.builtin.command: "sudo systemctl list-unit-files foreman.service"
      register: foreman_status
      changed_when: true
      tags:
        - tags_satellite_pre
        - tags_satellite_before_sync

    - name: "Assert that the foreman service exists"
      ansible.builtin.assert:
        that: "'foreman.service' in foreman_status.stdout"
      tags:
        - tags_satellite_pre
        - tags_satellite_before_sync

    - name: "Set _satpre_satellite_installed to true" # noqa var-naming[no-role-prefix]
      ansible.builtin.set_fact:
        _satpre_satellite_installed: true
      tags:
        - tags_satellite_pre
        - tags_satellite_before_sync

  rescue:
    - name: "Set _satpre_satellite_installed to false" # noqa var-naming[no-role-prefix]
      ansible.builtin.set_fact:
        _satpre_satellite_installed: false
      tags:
        - tags_satellite_pre
        - tags_satellite_before_sync

- name: "Debug output"
  ansible.builtin.debug:
    var: _satpre_satellite_installed
  tags:
    - tags_satellite_pre
    - tags_satellite_before_sync
