---

# perform a library or repository import
- name: "Ensure the destination path exists"
  ansible.builtin.file:
    path: "{{ content_import.import_path }}"
    state: "directory"
    mode: "0770"      # we need excute permissions on the directory and contents for pulp to function
    owner: "pulp"
    group: "pulp"
    recurse: true
    seuser: "system_u"     # satellite protects the pulp contents using SELinux
    serole: "object_r"
    setype: "pulpcore_var_lib_t"
    selevel: "s0"  # system_u:object_r:pulpcore_var_lib_t:s0

- name: "Ensure import directory permissions"
  ansible.builtin.stat:
    path: "{{ content_import.import_path }}"
  register: content_import_path_stat # noqa var-naming[no-role-prefix]

- name: "Assert"
  ansible.builtin.assert:
    that: content_import_path_stat.stat.exists

- name: "Important Note: The import task is next"
  ansible.builtin.debug:
    msg: >
      Import Tasks are long running, blocking tasks and may take hours to complete.
      We do not run async polling for these tasks as a timeout on the async poll will cause the playbook to fail.
      We just need to wait for the task to complete.
      The Satellite UI is up. If necessary, you can monitor the progress of the import via the Satellite Tasks status page.
      {{ satellite_url }}/foreman_tasks/tasks
      Please be patient.
  tags:
    - tags_content_config
    - tags_content_imports

- name: "Perform library import for {{ content_import.name }}"
  when: content_import.type == 'library'
  ansible.builtin.include_tasks: "perform_library_import.yml"
  tags:
    - tags_content_config
    - tags_content_imports
    - tags_library_imports

- name: "Perform repository import for {{ content_import.name }}"
  when: content_import.type == 'repository'
  ansible.builtin.include_tasks: "perform_repository_import.yml"
  tags:
    - tags_content_config
    - tags_content_imports
    - tags_repository_imports

- name: "Perform content_view import for {{ content_import.name }}"
  when: content_import.type == 'cv_version'
  ansible.builtin.include_tasks: "perform_cv_version_import.yml"
  tags:
    - tags_content_config
    - tags_content_imports
    - tags_content_view_imports
