---

- name: "Check GPG Key content"
  ansible.builtin.debug:
    var: content_credential.content

- name: "Ensure the state of the content credential - {{ content_credential.name }}"
  redhat.satellite.content_credential:
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    use_gssapi: "{{ satellite_use_gssapi | default(omit) }}"
    server_url: "{{ satellite_url }}"
    organization: "{{ satellite_organization }}"
    validate_certs: "{{ satellite_validate_certs }}"
    name: "{{ content_credential.name }}"
    ca_path: "{{ content_credential.ca_path | default(omit) }}"  # only for certificate credentials
    content: "{{ content_credential.content | default(omit) }}"
    content_type: "{{ content_credential.content_type }}"
    state: "{{ content_credential.state | default(omit) }}"
