---

# There are several ansible collections that need to be force updated
# right now it is only community.general and ansible.posix
# These are required to implement our OpenSCAP roles - they fail to run without these
# installed to /usr/share/ansible/roles

- name: "Force global location install of ansible collections" # noqa var-naming[no-role-prefix]
  when: force_global_ansible_collections is defined and (force_global_ansible_collection | length) > 0
  ansible.builtin.command: "ansible-galaxy collection install -p /usr/share/ansible/collections --force {{ global_collection }}"
  loop: "{{ force_global_ansible_collections }}"
  loop_control:
    loop_var: global_collection
  register: global_collections_result
  changed_when: global_collections_result == 0
