---

# Fetch files
- name: "Fetch tar the files"
  ansible.builtin.fetch:
    src: "/root/{{ cert_capsule.fqdn }}-certs.tar"
    dest: "/tmp/{{ cert_capsule.fqdn }}-certs.tar"
    flat: true

# Fetch files
- name: "Fetch script the files"
  ansible.builtin.fetch:
    src: "/root/{{ cert_capsule.fqdn }}-installer.sh"
    dest: "/tmp/{{ cert_capsule.fqdn }}-installer.sh"
    flat: true
