---

# yamllint disable rule:line-length
# Generate the capsule-certs.tar file for the capsule and the installer command
- name: "Define the secure directory"
  ansible.builtin.set_fact:
    capsule_crt_dir: "{{ private_crt_dir }}/{{ cert_capsule.fqdn }}/"

- name: "Define the capsule_cert_path"
  ansible.builtin.set_fact:
    capsule_crt_path: "{{ capsule_crt_dir }}{{ cert_capsule.fqdn }}.crt"
    capsule_key_path: "{{ capsule_crt_dir }}{{ cert_capsule.fqdn }}.key"
    capsule_csr_path: "{{ capsule_crt_dir }}{{ cert_capsule.fqdn }}.csr"
    capsule_private_key_pem_path: "{{ capsule_crt_dir }}{{ cert_capsule.fqdn }}.pem"
    capsule_ca_crt_path: "{{ capsule_crt_dir }}{{ cert_capsule.fqdn }}.CA.crt"

- name: "Generate the certificate bundle on the Satellite"
  ansible.builtin.command:
    cmd: "capsule-certs-generate --no-colors --foreman-proxy-fqdn {{ cert_capsule.fqdn }} --certs-tar '/root/{{ cert_capsule.fqdn }}-certs.tar' --server-cert {{ capsule_crt_path }} --server-key  {{ capsule_key_path }} --server-ca-cert {{ capsule_ca_crt_path }}" # noqa yaml[line-length]
  changed_when: true
  register: certs_gen

- name: "Instructions for installing capsule {{ cert_capsule.fqdn }}"
  ansible.builtin.debug:
    var: certs_gen.stdout

- name: "Store the results"
  ansible.builtin.copy:
    content: "{{ certs_gen.stdout }}"
    dest: "/root/{{ cert_capsule.fqdn }}-installer.sh"
    mode: "0700"

- name: "File cleaning"
  ansible.builtin.command: "echo ' ' >>  /root/{{ cert_capsule.fqdn }}-installer.sh"
  changed_when: true

- name: "Create the command script"
  ansible.builtin.command: "sed -i -n '/^  satellite-installer/,$p' /root/{{ cert_capsule.fqdn }}-installer.sh" # noqa command-instead-of-module
  changed_when: true

- name: "Add the whole shebang"
  ansible.builtin.command: 'sed -i "1i #!/bin/bash" /root/{{ cert_capsule.fqdn }}-installer.sh' # noqa command-instead-of-module
  changed_when: true

# append additional commandline args to the script

# TODO:
# enable OpenSCAP scanning on capsules
# --enable-foreman-proxy-plugin-openscap \
# --foreman-proxy-plugin-openscap-puppet-module true
#
# enable BMC power management
# --foreman-proxy-bmc "true" \
# --foreman-proxy-bmc-default-provider "freeipmi"
#
# enable dns, dhcp, tftp
# --foreman-proxy-dns true \
# --foreman-proxy-dns-managed true \
# --foreman-proxy-dns-interface eth0 \
# --foreman-proxy-dns-zone example.com \
# --foreman-proxy-dns-reverse 2.0.192.in-addr.arpa \
# --foreman-proxy-dhcp true \
# --foreman-proxy-dhcp-managed true \
# --foreman-proxy-dhcp-interface eth0 \
# --foreman-proxy-dhcp-additional-interfaces eth1 \
# --foreman-proxy-dhcp-additional-interfaces eth2 \
# --foreman-proxy-dhcp-range "192.0.2.100 192.0.2.150" \
# --foreman-proxy-dhcp-gateway 192.0.2.1 \
# --foreman-proxy-dhcp-nameservers 192.0.2.2 \
# --foreman-proxy-tftp true \
# --foreman-proxy-tftp-managed true \
# --foreman-proxy-tftp-servername 192.0.2.3
