---
# Activation keys that we use in the RH-ISAM

aks_rhisam:
  - name: "SOE_RHEL8"
    state: "present"
    description: "Activate a RHEL 8 system"
    organization: "{{ satellite_organization }}"
    auto_attach: false
    content_overrides:
      - label: "satellite-client-6-for-rhel-8-x86_64-rpms"
        override: "enabled"
    content_view: "SOE_RHEL8"
    lifecycle_environment: "Development"
    unlimited_hosts: true

  - name: "SOE_JBoss"
    state: "present"
    description: "Activate a RHEL8 SOE_JBoss system"
    organization: "{{ satellite_organization }}"
    auto_attach: false
    content_overrides:
      - label: "satellite-client-6-for-rhel-8-x86_64-rpms"
        override: "enabled"
      - label: "jb-eap-7.4-for-rhel-8-x86_64-rpms"
        override: "enabled"
    content_view: "SOE_JBoss"
    lifecycle_environment: "Development"
    unlimited_hosts: true

  - name: "SOE_RHEL9"
    state: "present"
    description: "Activate a RHEL 9 system"
    organization: "{{ satellite_organization }}"
    auto_attach: false
    content_overrides:
      - label: "satellite-client-6-for-rhel-9-x86_64-rpms"
        override: "enabled"
    content_view: "SOE_RHEL9"
    lifecycle_environment: "Development"
    unlimited_hosts: true

aks_user:
  - name: "SOE_RHEL7"
    state: "present"
    description: "Activate a RHEL 7 system"
    organization: "{{ satellite_organization }}"
    auto_attach: false
    content_overrides:
      - label: "rhel-7-server-satellite-client-6-rpms"
        override: "enabled"
    content_view: "SOE_RHEL7"
    lifecycle_environment: "Development"
    unlimited_hosts: true

  - name: "LEAPP_7_2_8"
    state: "present"
    description: "Migrate a RHEL 7 system to RHEL 8"
    organization: "{{ satellite_organization }}"
    auto_attach: false
    content_overrides:
      - label: "rhel-7-server-extras-rpms"
        override: "enabled"
    content_view: "LEAPP_7_2_8"
    lifecycle_environment: "Development"
    unlimited_hosts: true

  - name: "LEAPP_8_2_9"
    state: "present"
    description: "Migrate a RHEL 8 system to RHEL 9"
    organization: "{{ satellite_organization }}"
    auto_attach: false
    content_overrides:
      - label: "rhel-8-for-x86_64-supplementary-rpms"
        override: "disabled"
    content_view: "LEAPP_8_2_9"
    lifecycle_environment: "Development"
    unlimited_hosts: true
