---

- name: "Ensure the state of the satellite organization - {{ sat_organization.name }}"
  redhat.satellite.organization:
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    use_gssapi: "{{ satellite_use_gssapi | default(omit) }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_validate_certs | default(omit) }}"
    state: "{{ sat_organization.state | default(omit) }}"
    description: "{{ sat_organization.description | default(omit) }}"
    name: "{{ sat_organization.name }}"
    label: "{{ sat_organization.label | default(omit) }}"
    select_all_types: "{{ sat_organization.select_all_types | default(omit) }}"
    ignore_types: "{{ sat_organization.ignore_types | default(omit) }}"
    parameters: "{{ sat_organization.parameters | default('[]') }}"
